"""feat_isolation_and_interoperability_v2

Revision ID: 83f165c7d3c2
Revises: 7d8e9f0a1b2c
Create Date: 2026-05-05 22:41:01.314606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f165c7d3c2'
down_revision: Union[str, Sequence[str], None] = '7d8e9f0a1b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('bitacora_recuperacion')
    # op.drop_table('historial_cambios')
    # op.drop_table('sesiones_invalidas')
    # op.drop_table('auditoria_exportaciones')
    # op.drop_table('permisos_rol')
    # op.drop_table('cat_modulos')
    # op.drop_table('permisos_especialidad')
    # op.drop_table('jurisdicciones_sanitarias')
    # op.add_column('alergias', sa.Column('motivo_baja', sa.String(), nullable=True)) # Duplicate: already added in 7d8e9f0a1b2c
    op.alter_column('alergias', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('alergias', 'alergia',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('alergias', 'severidad',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('alergias_id_paciente_fkey'), 'alergias', type_='foreignkey')
    op.drop_constraint(op.f('alergias_eliminado_por_fkey'), 'alergias', type_='foreignkey')
    op.drop_constraint(op.f('alergias_registrado_por_fkey'), 'alergias', type_='foreignkey')
    op.create_foreign_key(op.f('fk_alergias_eliminado_por_usuarios_sistema'), 'alergias', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_alergias_registrado_por_usuarios_sistema'), 'alergias', 'usuarios_sistema', ['registrado_por'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_alergias_id_paciente_pacientes'), 'alergias', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.alter_column('antecedentes_ginecoobstetricos', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('antecedentes_ginecoobstetricos_id_paciente_fkey'), 'antecedentes_ginecoobstetricos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_antecedentes_ginecoobstetricos_eliminado_por_usuarios_sistema'), 'antecedentes_ginecoobstetricos', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_antecedentes_ginecoobstetricos_id_paciente_pacientes'), 'antecedentes_ginecoobstetricos', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.alter_column('antecedentes_heredofamiliares', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('antecedentes_heredofamiliares_id_paciente_fkey'), 'antecedentes_heredofamiliares', type_='foreignkey')
    op.create_foreign_key(op.f('fk_antecedentes_heredofamiliares_id_paciente_pacientes'), 'antecedentes_heredofamiliares', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.create_foreign_key(op.f('fk_antecedentes_heredofamiliares_eliminado_por_usuarios_sistema'), 'antecedentes_heredofamiliares', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.alter_column('antecedentes_no_patologicos', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('antecedentes_no_patologicos_id_paciente_fkey'), 'antecedentes_no_patologicos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_antecedentes_no_patologicos_eliminado_por_usuarios_sistema'), 'antecedentes_no_patologicos', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_antecedentes_no_patologicos_id_paciente_pacientes'), 'antecedentes_no_patologicos', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.alter_column('antecedentes_patologicos', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('antecedentes_patologicos_id_paciente_fkey'), 'antecedentes_patologicos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_antecedentes_patologicos_id_paciente_pacientes'), 'antecedentes_patologicos', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.create_foreign_key(op.f('fk_antecedentes_patologicos_eliminado_por_usuarios_sistema'), 'antecedentes_patologicos', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.alter_column('auditoria_accesos', 'direccion_ip',
               existing_type=postgresql.INET(),
               nullable=True)
    op.alter_column('auditoria_accesos', 'resultado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('auditoria_accesos', 'nivel_severidad',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('auditoria_accesos', 'detalles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_auditoria_accesos_id_auditoria'), 'auditoria_accesos', ['id_auditoria'], unique=False)
    op.create_foreign_key(op.f('fk_auditoria_accesos_id_usuario_usuarios_sistema'), 'auditoria_accesos', 'usuarios_sistema', ['id_usuario'], ['id_usuario'])
    op.drop_constraint(op.f('cat_cie10_codigo_padre_fkey'), 'cat_cie10', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cat_cie10_codigo_padre_cat_cie10'), 'cat_cie10', 'cat_cie10', ['codigo_padre'], ['codigo_cie'])
    op.alter_column('cat_localidades', 'id_municipio',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.drop_constraint(op.f('cat_localidades_id_municipio_fkey'), 'cat_localidades', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cat_localidades_id_municipio_cat_municipios'), 'cat_localidades', 'cat_municipios', ['id_municipio'], ['id_municipio'])
    op.alter_column('cat_medicamentos', 'nombre_generico',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('cat_medicamentos', 'presentacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('cat_medicamentos', 'forma_farmaceutica',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    # op.drop_column('cat_medicamentos', 'concentracion')
    op.alter_column('cat_municipios', 'id_estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.drop_constraint(op.f('cat_municipios_id_estado_fkey'), 'cat_municipios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cat_municipios_id_estado_cat_estados'), 'cat_municipios', 'cat_estados', ['id_estado'], ['id_estado'])
    op.drop_constraint(op.f('diagnosticos_encuentro_id_encuentro_fkey'), 'diagnosticos_encuentro', type_='foreignkey')
    op.drop_constraint(op.f('diagnosticos_encuentro_codigo_cie_fkey'), 'diagnosticos_encuentro', type_='foreignkey')
    op.create_foreign_key(op.f('fk_diagnosticos_encuentro_id_encuentro_encuentros_clinicos'), 'diagnosticos_encuentro', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'])
    op.create_foreign_key(op.f('fk_diagnosticos_encuentro_codigo_cie_cat_cie10'), 'diagnosticos_encuentro', 'cat_cie10', ['codigo_cie'], ['codigo_cie'])
    op.drop_constraint(op.f('encuentros_clinicos_id_paciente_fkey'), 'encuentros_clinicos', type_='foreignkey')
    op.drop_constraint(op.f('encuentros_clinicos_id_establecimiento_fkey'), 'encuentros_clinicos', type_='foreignkey')
    op.drop_constraint(op.f('encuentros_clinicos_id_especialidad_fkey'), 'encuentros_clinicos', type_='foreignkey')
    op.drop_constraint(op.f('encuentros_clinicos_id_medico_fkey'), 'encuentros_clinicos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_encuentros_clinicos_id_paciente_pacientes'), 'encuentros_clinicos', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.create_foreign_key(op.f('fk_encuentros_clinicos_id_especialidad_cat_especialidades_medicas'), 'encuentros_clinicos', 'cat_especialidades_medicas', ['id_especialidad'], ['id_especialidad'])
    op.create_foreign_key(op.f('fk_encuentros_clinicos_id_establecimiento_establecimientos'), 'encuentros_clinicos', 'establecimientos', ['id_establecimiento'], ['id_establecimiento'])
    op.create_foreign_key(op.f('fk_encuentros_clinicos_id_medico_usuarios_sistema'), 'encuentros_clinicos', 'usuarios_sistema', ['id_medico'], ['id_usuario'])
    op.drop_constraint(op.f('establecimientos_clues_key'), 'establecimientos', type_='unique')
    op.create_unique_constraint(op.f('uq_establecimientos_clues'), 'establecimientos', ['clues'])
    op.drop_constraint(op.f('establecimientos_id_localidad_fkey'), 'establecimientos', type_='foreignkey')
    op.drop_constraint(op.f('establecimientos_id_jurisdiccion_fkey'), 'establecimientos', type_='foreignkey')
    op.alter_column('establecimientos_especialidades', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('establecimientos_especialidades_id_especialidad_fkey'), 'establecimientos_especialidades', type_='foreignkey')
    op.drop_constraint(op.f('establecimientos_especialidades_id_establecimiento_fkey'), 'establecimientos_especialidades', type_='foreignkey')
    op.create_foreign_key(op.f('fk_establecimientos_especialidades_id_establecimiento_establecimientos'), 'establecimientos_especialidades', 'establecimientos', ['id_establecimiento'], ['id_establecimiento'])
    op.create_foreign_key(op.f('fk_establecimientos_especialidades_id_especialidad_cat_especialidades_medicas'), 'establecimientos_especialidades', 'cat_especialidades_medicas', ['id_especialidad'], ['id_especialidad'])
    op.alter_column('incidentes_seguridad', 'id_auditoria',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('incidentes_seguridad_id_auditoria_fkey'), 'incidentes_seguridad', type_='foreignkey')
    op.create_foreign_key(op.f('fk_incidentes_seguridad_id_auditoria_auditoria_accesos'), 'incidentes_seguridad', 'auditoria_accesos', ['id_auditoria'], ['id_auditoria'])
    # op.drop_column('incidentes_seguridad', 'vulnerabilidad_explotada')
    op.alter_column('inmunizaciones', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('inmunizaciones_id_paciente_fkey'), 'inmunizaciones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inmunizaciones_eliminado_por_usuarios_sistema'), 'inmunizaciones', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_inmunizaciones_id_paciente_pacientes'), 'inmunizaciones', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.alter_column('notas_enmienda', 'id_nota',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('notas_enmienda_id_nota_fkey'), 'notas_enmienda', type_='foreignkey')
    op.drop_constraint(op.f('notas_enmienda_id_medico_fkey'), 'notas_enmienda', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notas_enmienda_id_nota_notas_medicas'), 'notas_enmienda', 'notas_medicas', ['id_nota'], ['id_nota'])
    op.create_foreign_key(op.f('fk_notas_enmienda_id_medico_usuarios_sistema'), 'notas_enmienda', 'usuarios_sistema', ['id_medico'], ['id_usuario'])
    op.alter_column('notas_medicas', 'id_encuentro',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('notas_medicas_id_encuentro_fkey'), 'notas_medicas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notas_medicas_id_encuentro_encuentros_clinicos'), 'notas_medicas', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'])
    op.drop_constraint(op.f('notas_soap_detalle_id_nota_fkey'), 'notas_soap_detalle', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notas_soap_detalle_id_nota_notas_medicas'), 'notas_soap_detalle', 'notas_medicas', ['id_nota'], ['id_nota'])
    op.alter_column('pacientes', 'id_persona',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pacientes', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pacientes', 'motivo_baja',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('pacientes_id_persona_key'), 'pacientes', type_='unique')
    op.drop_constraint(op.f('pacientes_numero_expediente_key'), 'pacientes', type_='unique')
    op.create_unique_constraint(op.f('uq_pacientes_id_persona'), 'pacientes', ['id_persona'])
    op.create_unique_constraint(op.f('uq_pacientes_numero_expediente'), 'pacientes', ['numero_expediente'])
    op.drop_constraint(op.f('pacientes_id_persona_fkey'), 'pacientes', type_='foreignkey')
    op.drop_constraint(op.f('pacientes_eliminado_por_fkey'), 'pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pacientes_id_persona_personas'), 'pacientes', 'personas', ['id_persona'], ['id_persona'])
    op.create_foreign_key(op.f('fk_pacientes_eliminado_por_usuarios_sistema'), 'pacientes', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.add_column('pacientes_tutores_representantes', sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pacientes_tutores_representantes', sa.Column('eliminado_por', sa.UUID(), nullable=True))
    op.add_column('pacientes_tutores_representantes', sa.Column('motivo_baja', sa.String(), nullable=True))
    op.alter_column('pacientes_tutores_representantes', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pacientes_tutores_representantes', 'id_persona',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pacientes_tutores_representantes', 'documento_legal_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('pacientes_tutores_representantes_id_persona_fkey'), 'pacientes_tutores_representantes', type_='foreignkey')
    op.drop_constraint(op.f('pacientes_tutores_representantes_id_paciente_fkey'), 'pacientes_tutores_representantes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pacientes_tutores_representantes_id_paciente_pacientes'), 'pacientes_tutores_representantes', 'pacientes', ['id_paciente'], ['id_paciente'])
    op.create_foreign_key(op.f('fk_pacientes_tutores_representantes_id_persona_personas'), 'pacientes_tutores_representantes', 'personas', ['id_persona'], ['id_persona'])
    op.create_foreign_key(op.f('fk_pacientes_tutores_representantes_eliminado_por_usuarios_sistema'), 'pacientes_tutores_representantes', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'])
    op.alter_column('personas', 'sexo',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               nullable=False)
    op.alter_column('personas', 'calle_numero',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('personas', 'referencia_geografica',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('personas', 'url_foto',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('personas', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('personas_curp_key'), 'personas', type_='unique')
    op.create_unique_constraint(op.f('uq_personas_curp'), 'personas', ['curp'])
    op.drop_constraint(op.f('personas_id_lengua_materna_fkey'), 'personas', type_='foreignkey')
    op.drop_constraint(op.f('personas_id_localidad_fkey'), 'personas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_personas_id_lengua_materna_cat_lenguas_indigenas'), 'personas', 'cat_lenguas_indigenas', ['id_lengua_materna'], ['id_lengua'])
    op.create_foreign_key(op.f('fk_personas_id_localidad_cat_localidades'), 'personas', 'cat_localidades', ['id_localidad'], ['id_localidad'])
    op.alter_column('prescripciones', 'id_encuentro',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('prescripciones', 'codigo_medicamento_ssa',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('prescripciones_codigo_medicamento_ssa_fkey'), 'prescripciones', type_='foreignkey')
    op.drop_constraint(op.f('prescripciones_id_encuentro_fkey'), 'prescripciones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prescripciones_id_encuentro_encuentros_clinicos'), 'prescripciones', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'])
    op.create_foreign_key(op.f('fk_prescripciones_codigo_medicamento_ssa_cat_medicamentos'), 'prescripciones', 'cat_medicamentos', ['codigo_medicamento_ssa'], ['codigo_medicamento_ssa'])
    op.add_column('referencias_medicas', sa.Column('folio', sa.String(length=20), nullable=True))
    op.add_column('referencias_medicas', sa.Column('tipo', sa.String(length=20), server_default='REFERENCIA', nullable=False))
    op.add_column('referencias_medicas', sa.Column('id_referencia_origen', sa.UUID(), nullable=True))
    op.add_column('referencias_medicas', sa.Column('urgencia', sa.String(length=20), nullable=True))
    op.add_column('referencias_medicas', sa.Column('diagnostico_cie10', sa.String(length=10), nullable=True))
    op.add_column('referencias_medicas', sa.Column('resumen_contrarreferencia', sa.Text(), nullable=True))
    op.add_column('referencias_medicas', sa.Column('id_usuario_emisor', sa.UUID(), nullable=True))
    op.add_column('referencias_medicas', sa.Column('id_usuario_respuesta', sa.UUID(), nullable=True))
    op.alter_column('referencias_medicas', 'id_encuentro_origen',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('referencias_medicas', 'id_establecimiento_destino',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('referencias_medicas', 'id_especialidad_destino',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referencias_medicas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(op.f('uq_referencias_medicas_folio'), 'referencias_medicas', ['folio'])
    op.drop_constraint(op.f('referencias_medicas_id_especialidad_destino_fkey'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('referencias_medicas_id_encuentro_origen_fkey'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('referencias_medicas_id_establecimiento_destino_fkey'), 'referencias_medicas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_referencias_medicas_id_usuario_respuesta_usuarios_sistema'), 'referencias_medicas', 'usuarios_sistema', ['id_usuario_respuesta'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_referencias_medicas_id_encuentro_origen_encuentros_clinicos'), 'referencias_medicas', 'encuentros_clinicos', ['id_encuentro_origen'], ['id_encuentro'])
    op.create_foreign_key(op.f('fk_referencias_medicas_id_usuario_emisor_usuarios_sistema'), 'referencias_medicas', 'usuarios_sistema', ['id_usuario_emisor'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_referencias_medicas_id_especialidad_destino_cat_especialidades_medicas'), 'referencias_medicas', 'cat_especialidades_medicas', ['id_especialidad_destino'], ['id_especialidad'])
    op.create_foreign_key(op.f('fk_referencias_medicas_id_establecimiento_destino_establecimientos'), 'referencias_medicas', 'establecimientos', ['id_establecimiento_destino'], ['id_establecimiento'])
    op.create_foreign_key(op.f('fk_referencias_medicas_id_referencia_origen_referencias_medicas'), 'referencias_medicas', 'referencias_medicas', ['id_referencia_origen'], ['id_referencia'])
    op.alter_column('resultados_laboratorio', 'id_solicitud',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('resultados_laboratorio', 'subido_por',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('resultados_laboratorio_id_solicitud_fkey'), 'resultados_laboratorio', type_='foreignkey')
    op.drop_constraint(op.f('resultados_laboratorio_subido_por_fkey'), 'resultados_laboratorio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_resultados_laboratorio_id_solicitud_solicitudes_estudio'), 'resultados_laboratorio', 'solicitudes_estudio', ['id_solicitud'], ['id_solicitud'])
    op.create_foreign_key(op.f('fk_resultados_laboratorio_subido_por_usuarios_sistema'), 'resultados_laboratorio', 'usuarios_sistema', ['subido_por'], ['id_usuario'])
    op.alter_column('roles', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('roles_codigo_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_codigo'), 'roles', ['codigo'])
    op.drop_index(op.f('ix_sesiones_activas_fecha_expira'), table_name='sesiones_activas')
    op.drop_index(op.f('ix_sesiones_activas_id_usuario'), table_name='sesiones_activas')
    op.drop_constraint(op.f('sesiones_activas_id_usuario_fkey'), 'sesiones_activas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sesiones_activas_id_usuario_usuarios_sistema'), 'sesiones_activas', 'usuarios_sistema', ['id_usuario'], ['id_usuario'])
    op.drop_constraint(op.f('signos_vitales_id_encuentro_fkey'), 'signos_vitales', type_='foreignkey')
    op.drop_constraint(op.f('signos_vitales_id_enfermero_fkey'), 'signos_vitales', type_='foreignkey')
    op.create_foreign_key(op.f('fk_signos_vitales_id_enfermero_usuarios_sistema'), 'signos_vitales', 'usuarios_sistema', ['id_enfermero'], ['id_usuario'])
    op.create_foreign_key(op.f('fk_signos_vitales_id_encuentro_encuentros_clinicos'), 'signos_vitales', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'])
    op.alter_column('solicitudes_estudio', 'id_encuentro',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('solicitudes_estudio', 'urgente',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('solicitudes_estudio_id_encuentro_fkey'), 'solicitudes_estudio', type_='foreignkey')
    op.drop_constraint(op.f('solicitudes_estudio_id_cie10_relacionado_fkey'), 'solicitudes_estudio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_solicitudes_estudio_id_encuentro_encuentros_clinicos'), 'solicitudes_estudio', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'])
    op.create_foreign_key(op.f('fk_solicitudes_estudio_id_cie10_relacionado_cat_cie10'), 'solicitudes_estudio', 'cat_cie10', ['id_cie10_relacionado'], ['codigo_cie'])
    op.drop_constraint(op.f('usuarios_establecimientos_id_usuario_fkey'), 'usuarios_establecimientos', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_establecimientos_id_establecimiento_fkey'), 'usuarios_establecimientos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_establecimientos_id_establecimiento_establecimientos'), 'usuarios_establecimientos', 'establecimientos', ['id_establecimiento'], ['id_establecimiento'])
    op.create_foreign_key(op.f('fk_usuarios_establecimientos_id_usuario_usuarios_sistema'), 'usuarios_establecimientos', 'usuarios_sistema', ['id_usuario'], ['id_usuario'])
    op.drop_index(op.f('ix_usuarios_ips_confiables_id_usuario'), table_name='usuarios_ips_confiables')
    op.create_index(op.f('ix_usuarios_ips_confiables_id_confianza'), 'usuarios_ips_confiables', ['id_confianza'], unique=False)
    op.drop_constraint(op.f('usuarios_ips_confiables_id_usuario_fkey'), 'usuarios_ips_confiables', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_ips_confiables_id_usuario_usuarios_sistema'), 'usuarios_ips_confiables', 'usuarios_sistema', ['id_usuario'], ['id_usuario'])
    op.drop_constraint(op.f('usuarios_sistema_email_key'), 'usuarios_sistema', type_='unique')
    op.create_unique_constraint(op.f('uq_usuarios_sistema_email'), 'usuarios_sistema', ['email'])
    op.drop_constraint(op.f('usuarios_sistema_id_persona_fkey'), 'usuarios_sistema', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_sistema_id_rol_fkey'), 'usuarios_sistema', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_sistema_id_persona_personas'), 'usuarios_sistema', 'personas', ['id_persona'], ['id_persona'])
    op.create_foreign_key(op.f('fk_usuarios_sistema_id_rol_roles'), 'usuarios_sistema', 'roles', ['id_rol'], ['id_rol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_usuarios_sistema_id_rol_roles'), 'usuarios_sistema', type_='foreignkey')
    op.drop_constraint(op.f('fk_usuarios_sistema_id_persona_personas'), 'usuarios_sistema', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_sistema_id_rol_fkey'), 'usuarios_sistema', 'roles', ['id_rol'], ['id_rol'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('usuarios_sistema_id_persona_fkey'), 'usuarios_sistema', 'personas', ['id_persona'], ['id_persona'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_usuarios_sistema_email'), 'usuarios_sistema', type_='unique')
    op.create_unique_constraint(op.f('usuarios_sistema_email_key'), 'usuarios_sistema', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_usuarios_ips_confiables_id_usuario_usuarios_sistema'), 'usuarios_ips_confiables', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_ips_confiables_id_usuario_fkey'), 'usuarios_ips_confiables', 'usuarios_sistema', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
    op.drop_index(op.f('ix_usuarios_ips_confiables_id_confianza'), table_name='usuarios_ips_confiables')
    op.create_index(op.f('ix_usuarios_ips_confiables_id_usuario'), 'usuarios_ips_confiables', ['id_usuario'], unique=False)
    op.drop_constraint(op.f('fk_usuarios_establecimientos_id_usuario_usuarios_sistema'), 'usuarios_establecimientos', type_='foreignkey')
    op.drop_constraint(op.f('fk_usuarios_establecimientos_id_establecimiento_establecimientos'), 'usuarios_establecimientos', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_establecimientos_id_establecimiento_fkey'), 'usuarios_establecimientos', 'establecimientos', ['id_establecimiento'], ['id_establecimiento'], ondelete='CASCADE')
    op.create_foreign_key(op.f('usuarios_establecimientos_id_usuario_fkey'), 'usuarios_establecimientos', 'usuarios_sistema', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_solicitudes_estudio_id_cie10_relacionado_cat_cie10'), 'solicitudes_estudio', type_='foreignkey')
    op.drop_constraint(op.f('fk_solicitudes_estudio_id_encuentro_encuentros_clinicos'), 'solicitudes_estudio', type_='foreignkey')
    op.create_foreign_key(op.f('solicitudes_estudio_id_cie10_relacionado_fkey'), 'solicitudes_estudio', 'cat_cie10', ['id_cie10_relacionado'], ['codigo_cie'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('solicitudes_estudio_id_encuentro_fkey'), 'solicitudes_estudio', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'], ondelete='CASCADE')
    op.alter_column('solicitudes_estudio', 'urgente',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('solicitudes_estudio', 'id_encuentro',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_signos_vitales_id_encuentro_encuentros_clinicos'), 'signos_vitales', type_='foreignkey')
    op.drop_constraint(op.f('fk_signos_vitales_id_enfermero_usuarios_sistema'), 'signos_vitales', type_='foreignkey')
    op.create_foreign_key(op.f('signos_vitales_id_enfermero_fkey'), 'signos_vitales', 'usuarios_sistema', ['id_enfermero'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('signos_vitales_id_encuentro_fkey'), 'signos_vitales', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_sesiones_activas_id_usuario_usuarios_sistema'), 'sesiones_activas', type_='foreignkey')
    op.create_foreign_key(op.f('sesiones_activas_id_usuario_fkey'), 'sesiones_activas', 'usuarios_sistema', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
    op.create_index(op.f('ix_sesiones_activas_id_usuario'), 'sesiones_activas', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_sesiones_activas_fecha_expira'), 'sesiones_activas', ['fecha_expira'], unique=False)
    op.drop_constraint(op.f('uq_roles_codigo'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.create_unique_constraint(op.f('roles_codigo_key'), 'roles', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_resultados_laboratorio_subido_por_usuarios_sistema'), 'resultados_laboratorio', type_='foreignkey')
    op.drop_constraint(op.f('fk_resultados_laboratorio_id_solicitud_solicitudes_estudio'), 'resultados_laboratorio', type_='foreignkey')
    op.create_foreign_key(op.f('resultados_laboratorio_subido_por_fkey'), 'resultados_laboratorio', 'usuarios_sistema', ['subido_por'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('resultados_laboratorio_id_solicitud_fkey'), 'resultados_laboratorio', 'solicitudes_estudio', ['id_solicitud'], ['id_solicitud'], ondelete='RESTRICT')
    op.alter_column('resultados_laboratorio', 'subido_por',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('resultados_laboratorio', 'id_solicitud',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_referencias_medicas_id_referencia_origen_referencias_medicas'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('fk_referencias_medicas_id_establecimiento_destino_establecimientos'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('fk_referencias_medicas_id_especialidad_destino_cat_especialidades_medicas'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('fk_referencias_medicas_id_usuario_emisor_usuarios_sistema'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('fk_referencias_medicas_id_encuentro_origen_encuentros_clinicos'), 'referencias_medicas', type_='foreignkey')
    op.drop_constraint(op.f('fk_referencias_medicas_id_usuario_respuesta_usuarios_sistema'), 'referencias_medicas', type_='foreignkey')
    op.create_foreign_key(op.f('referencias_medicas_id_establecimiento_destino_fkey'), 'referencias_medicas', 'establecimientos', ['id_establecimiento_destino'], ['id_establecimiento'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('referencias_medicas_id_encuentro_origen_fkey'), 'referencias_medicas', 'encuentros_clinicos', ['id_encuentro_origen'], ['id_encuentro'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('referencias_medicas_id_especialidad_destino_fkey'), 'referencias_medicas', 'cat_especialidades_medicas', ['id_especialidad_destino'], ['id_especialidad'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_referencias_medicas_folio'), 'referencias_medicas', type_='unique')
    op.alter_column('referencias_medicas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('referencias_medicas', 'id_especialidad_destino',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referencias_medicas', 'id_establecimiento_destino',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('referencias_medicas', 'id_encuentro_origen',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('referencias_medicas', 'id_usuario_respuesta')
    op.drop_column('referencias_medicas', 'id_usuario_emisor')
    op.drop_column('referencias_medicas', 'resumen_contrarreferencia')
    op.drop_column('referencias_medicas', 'diagnostico_cie10')
    op.drop_column('referencias_medicas', 'urgencia')
    op.drop_column('referencias_medicas', 'id_referencia_origen')
    op.drop_column('referencias_medicas', 'tipo')
    op.drop_column('referencias_medicas', 'folio')
    op.drop_constraint(op.f('fk_prescripciones_codigo_medicamento_ssa_cat_medicamentos'), 'prescripciones', type_='foreignkey')
    op.drop_constraint(op.f('fk_prescripciones_id_encuentro_encuentros_clinicos'), 'prescripciones', type_='foreignkey')
    op.create_foreign_key(op.f('prescripciones_id_encuentro_fkey'), 'prescripciones', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'], ondelete='CASCADE')
    op.create_foreign_key(op.f('prescripciones_codigo_medicamento_ssa_fkey'), 'prescripciones', 'cat_medicamentos', ['codigo_medicamento_ssa'], ['codigo_medicamento_ssa'], ondelete='RESTRICT')
    op.alter_column('prescripciones', 'codigo_medicamento_ssa',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('prescripciones', 'id_encuentro',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_personas_id_localidad_cat_localidades'), 'personas', type_='foreignkey')
    op.drop_constraint(op.f('fk_personas_id_lengua_materna_cat_lenguas_indigenas'), 'personas', type_='foreignkey')
    op.create_foreign_key(op.f('personas_id_localidad_fkey'), 'personas', 'cat_localidades', ['id_localidad'], ['id_localidad'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('personas_id_lengua_materna_fkey'), 'personas', 'cat_lenguas_indigenas', ['id_lengua_materna'], ['id_lengua'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_personas_curp'), 'personas', type_='unique')
    op.create_unique_constraint(op.f('personas_curp_key'), 'personas', ['curp'], postgresql_nulls_not_distinct=False)
    op.alter_column('personas', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('personas', 'url_foto',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('personas', 'referencia_geografica',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('personas', 'calle_numero',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('personas', 'sexo',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               nullable=True)
    op.drop_constraint(op.f('fk_pacientes_tutores_representantes_eliminado_por_usuarios_sistema'), 'pacientes_tutores_representantes', type_='foreignkey')
    op.drop_constraint(op.f('fk_pacientes_tutores_representantes_id_persona_personas'), 'pacientes_tutores_representantes', type_='foreignkey')
    op.drop_constraint(op.f('fk_pacientes_tutores_representantes_id_paciente_pacientes'), 'pacientes_tutores_representantes', type_='foreignkey')
    op.create_foreign_key(op.f('pacientes_tutores_representantes_id_paciente_fkey'), 'pacientes_tutores_representantes', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pacientes_tutores_representantes_id_persona_fkey'), 'pacientes_tutores_representantes', 'personas', ['id_persona'], ['id_persona'], ondelete='RESTRICT')
    op.alter_column('pacientes_tutores_representantes', 'documento_legal_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pacientes_tutores_representantes', 'id_persona',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pacientes_tutores_representantes', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('pacientes_tutores_representantes', 'motivo_baja')
    op.drop_column('pacientes_tutores_representantes', 'eliminado_por')
    op.drop_column('pacientes_tutores_representantes', 'eliminado_en')
    op.drop_constraint(op.f('fk_pacientes_eliminado_por_usuarios_sistema'), 'pacientes', type_='foreignkey')
    op.drop_constraint(op.f('fk_pacientes_id_persona_personas'), 'pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('pacientes_eliminado_por_fkey'), 'pacientes', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('pacientes_id_persona_fkey'), 'pacientes', 'personas', ['id_persona'], ['id_persona'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_pacientes_numero_expediente'), 'pacientes', type_='unique')
    op.drop_constraint(op.f('uq_pacientes_id_persona'), 'pacientes', type_='unique')
    op.create_unique_constraint(op.f('pacientes_numero_expediente_key'), 'pacientes', ['numero_expediente'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('pacientes_id_persona_key'), 'pacientes', ['id_persona'], postgresql_nulls_not_distinct=False)
    op.alter_column('pacientes', 'motivo_baja',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pacientes', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pacientes', 'id_persona',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_notas_soap_detalle_id_nota_notas_medicas'), 'notas_soap_detalle', type_='foreignkey')
    op.create_foreign_key(op.f('notas_soap_detalle_id_nota_fkey'), 'notas_soap_detalle', 'notas_medicas', ['id_nota'], ['id_nota'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_notas_medicas_id_encuentro_encuentros_clinicos'), 'notas_medicas', type_='foreignkey')
    op.create_foreign_key(op.f('notas_medicas_id_encuentro_fkey'), 'notas_medicas', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'], ondelete='CASCADE')
    op.alter_column('notas_medicas', 'id_encuentro',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_notas_enmienda_id_medico_usuarios_sistema'), 'notas_enmienda', type_='foreignkey')
    op.drop_constraint(op.f('fk_notas_enmienda_id_nota_notas_medicas'), 'notas_enmienda', type_='foreignkey')
    op.create_foreign_key(op.f('notas_enmienda_id_medico_fkey'), 'notas_enmienda', 'usuarios_sistema', ['id_medico'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('notas_enmienda_id_nota_fkey'), 'notas_enmienda', 'notas_medicas', ['id_nota'], ['id_nota'], ondelete='RESTRICT')
    op.alter_column('notas_enmienda', 'id_nota',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_inmunizaciones_id_paciente_pacientes'), 'inmunizaciones', type_='foreignkey')
    op.drop_constraint(op.f('fk_inmunizaciones_eliminado_por_usuarios_sistema'), 'inmunizaciones', type_='foreignkey')
    op.create_foreign_key(op.f('inmunizaciones_id_paciente_fkey'), 'inmunizaciones', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.alter_column('inmunizaciones', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    # op.add_column('incidentes_seguridad', sa.Column('vulnerabilidad_explotada', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_incidentes_seguridad_id_auditoria_auditoria_accesos'), 'incidentes_seguridad', type_='foreignkey')
    op.create_foreign_key(op.f('incidentes_seguridad_id_auditoria_fkey'), 'incidentes_seguridad', 'auditoria_accesos', ['id_auditoria'], ['id_auditoria'], ondelete='RESTRICT')
    op.alter_column('incidentes_seguridad', 'id_auditoria',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('fk_establecimientos_especialidades_id_especialidad_cat_especialidades_medicas'), 'establecimientos_especialidades', type_='foreignkey')
    op.drop_constraint(op.f('fk_establecimientos_especialidades_id_establecimiento_establecimientos'), 'establecimientos_especialidades', type_='foreignkey')
    op.create_foreign_key(op.f('establecimientos_especialidades_id_establecimiento_fkey'), 'establecimientos_especialidades', 'establecimientos', ['id_establecimiento'], ['id_establecimiento'], ondelete='CASCADE')
    op.create_foreign_key(op.f('establecimientos_especialidades_id_especialidad_fkey'), 'establecimientos_especialidades', 'cat_especialidades_medicas', ['id_especialidad'], ['id_especialidad'], ondelete='CASCADE')
    op.alter_column('establecimientos_especialidades', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(op.f('establecimientos_id_jurisdiccion_fkey'), 'establecimientos', 'jurisdicciones_sanitarias', ['id_jurisdiccion'], ['id_jurisdiccion'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('establecimientos_id_localidad_fkey'), 'establecimientos', 'cat_localidades', ['id_localidad'], ['id_localidad'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_establecimientos_clues'), 'establecimientos', type_='unique')
    op.create_unique_constraint(op.f('establecimientos_clues_key'), 'establecimientos', ['clues'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_encuentros_clinicos_id_medico_usuarios_sistema'), 'encuentros_clinicos', type_='foreignkey')
    op.drop_constraint(op.f('fk_encuentros_clinicos_id_establecimiento_establecimientos'), 'encuentros_clinicos', type_='foreignkey')
    op.drop_constraint(op.f('fk_encuentros_clinicos_id_especialidad_cat_especialidades_medicas'), 'encuentros_clinicos', type_='foreignkey')
    op.drop_constraint(op.f('fk_encuentros_clinicos_id_paciente_pacientes'), 'encuentros_clinicos', type_='foreignkey')
    op.create_foreign_key(op.f('encuentros_clinicos_id_medico_fkey'), 'encuentros_clinicos', 'usuarios_sistema', ['id_medico'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('encuentros_clinicos_id_especialidad_fkey'), 'encuentros_clinicos', 'cat_especialidades_medicas', ['id_especialidad'], ['id_especialidad'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('encuentros_clinicos_id_establecimiento_fkey'), 'encuentros_clinicos', 'establecimientos', ['id_establecimiento'], ['id_establecimiento'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('encuentros_clinicos_id_paciente_fkey'), 'encuentros_clinicos', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_diagnosticos_encuentro_codigo_cie_cat_cie10'), 'diagnosticos_encuentro', type_='foreignkey')
    op.drop_constraint(op.f('fk_diagnosticos_encuentro_id_encuentro_encuentros_clinicos'), 'diagnosticos_encuentro', type_='foreignkey')
    op.create_foreign_key(op.f('diagnosticos_encuentro_codigo_cie_fkey'), 'diagnosticos_encuentro', 'cat_cie10', ['codigo_cie'], ['codigo_cie'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('diagnosticos_encuentro_id_encuentro_fkey'), 'diagnosticos_encuentro', 'encuentros_clinicos', ['id_encuentro'], ['id_encuentro'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_cat_municipios_id_estado_cat_estados'), 'cat_municipios', type_='foreignkey')
    op.create_foreign_key(op.f('cat_municipios_id_estado_fkey'), 'cat_municipios', 'cat_estados', ['id_estado'], ['id_estado'], ondelete='RESTRICT')
    op.alter_column('cat_municipios', 'id_estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # op.add_column('cat_medicamentos', sa.Column('concentracion', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('cat_medicamentos', 'forma_farmaceutica',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('cat_medicamentos', 'presentacion',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cat_medicamentos', 'nombre_generico',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_cat_localidades_id_municipio_cat_municipios'), 'cat_localidades', type_='foreignkey')
    op.create_foreign_key(op.f('cat_localidades_id_municipio_fkey'), 'cat_localidades', 'cat_municipios', ['id_municipio'], ['id_municipio'], ondelete='RESTRICT')
    op.alter_column('cat_localidades', 'id_municipio',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.drop_constraint(op.f('fk_cat_cie10_codigo_padre_cat_cie10'), 'cat_cie10', type_='foreignkey')
    op.create_foreign_key(op.f('cat_cie10_codigo_padre_fkey'), 'cat_cie10', 'cat_cie10', ['codigo_padre'], ['codigo_cie'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_auditoria_accesos_id_usuario_usuarios_sistema'), 'auditoria_accesos', type_='foreignkey')
    op.drop_index(op.f('ix_auditoria_accesos_id_auditoria'), table_name='auditoria_accesos')
    op.alter_column('auditoria_accesos', 'detalles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('auditoria_accesos', 'nivel_severidad',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('auditoria_accesos', 'resultado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('auditoria_accesos', 'direccion_ip',
               existing_type=postgresql.INET(),
               nullable=False)
    op.drop_constraint(op.f('fk_antecedentes_patologicos_eliminado_por_usuarios_sistema'), 'antecedentes_patologicos', type_='foreignkey')
    op.drop_constraint(op.f('fk_antecedentes_patologicos_id_paciente_pacientes'), 'antecedentes_patologicos', type_='foreignkey')
    op.create_foreign_key(op.f('antecedentes_patologicos_id_paciente_fkey'), 'antecedentes_patologicos', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.alter_column('antecedentes_patologicos', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_antecedentes_no_patologicos_id_paciente_pacientes'), 'antecedentes_no_patologicos', type_='foreignkey')
    op.drop_constraint(op.f('fk_antecedentes_no_patologicos_eliminado_por_usuarios_sistema'), 'antecedentes_no_patologicos', type_='foreignkey')
    op.create_foreign_key(op.f('antecedentes_no_patologicos_id_paciente_fkey'), 'antecedentes_no_patologicos', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.alter_column('antecedentes_no_patologicos', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_antecedentes_heredofamiliares_eliminado_por_usuarios_sistema'), 'antecedentes_heredofamiliares', type_='foreignkey')
    op.drop_constraint(op.f('fk_antecedentes_heredofamiliares_id_paciente_pacientes'), 'antecedentes_heredofamiliares', type_='foreignkey')
    op.create_foreign_key(op.f('antecedentes_heredofamiliares_id_paciente_fkey'), 'antecedentes_heredofamiliares', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.alter_column('antecedentes_heredofamiliares', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_antecedentes_ginecoobstetricos_id_paciente_pacientes'), 'antecedentes_ginecoobstetricos', type_='foreignkey')
    op.drop_constraint(op.f('fk_antecedentes_ginecoobstetricos_eliminado_por_usuarios_sistema'), 'antecedentes_ginecoobstetricos', type_='foreignkey')
    op.create_foreign_key(op.f('antecedentes_ginecoobstetricos_id_paciente_fkey'), 'antecedentes_ginecoobstetricos', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.alter_column('antecedentes_ginecoobstetricos', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_alergias_id_paciente_pacientes'), 'alergias', type_='foreignkey')
    op.drop_constraint(op.f('fk_alergias_registrado_por_usuarios_sistema'), 'alergias', type_='foreignkey')
    op.drop_constraint(op.f('fk_alergias_eliminado_por_usuarios_sistema'), 'alergias', type_='foreignkey')
    op.create_foreign_key(op.f('alergias_registrado_por_fkey'), 'alergias', 'usuarios_sistema', ['registrado_por'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('alergias_eliminado_por_fkey'), 'alergias', 'usuarios_sistema', ['eliminado_por'], ['id_usuario'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('alergias_id_paciente_fkey'), 'alergias', 'pacientes', ['id_paciente'], ['id_paciente'], ondelete='CASCADE')
    op.alter_column('alergias', 'severidad',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('alergias', 'alergia',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('alergias', 'id_paciente',
               existing_type=sa.UUID(),
               nullable=True)
    # op.drop_column('alergias', 'motivo_baja') # Duplicate: already handled in 7d8e9f0a1b2c
    # op.create_table('jurisdicciones_sanitarias', ... )
    # op.create_table('permisos_especialidad', ... )
    # op.create_table('cat_modulos', ... )
    # op.create_table('permisos_rol', ... )
    # op.create_table('auditoria_exportaciones', ... )
    # op.create_table('sesiones_invalidas', ... )
    # op.create_table('historial_cambios', ... )
    # op.create_table('bitacora_recuperacion', ... )
    # ### end Alembic commands ###
